on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: spencerbeggs/aws-jsii-action@test2
            - run: npm build
            - run: npm package
            - run: ls
