on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: spencerbeggs/aws-jsii-action@test2
            - run: npm install
            - run: npm run build
            - run: npm run package
            - run: ls
